
cd openpose 
./build/examples/openpose/openpose.bin  --video ./videos/sitting/sitting_0.mp4 --write_video ./videos/output/sitting/sitting_0.mp4 --write_json ./videos/output/sitting/keypoints_sitting_0.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sitting/sitting_1.mp4 --write_video ./videos/output/sitting/sitting_1.mp4 --write_json ./videos/output/sitting/keypoints_sitting_1.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sitting/sitting_2.mp4 --write_video ./videos/output/sitting/sitting_2.mp4 --write_json ./videos/output/sitting/keypoints_sitting_2.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sitting/sitting_3.mp4 --write_video ./videos/output/sitting/sitting_3.mp4 --write_json ./videos/output/sitting/keypoints_sitting_3.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1

./build/examples/openpose/openpose.bin  --video ./videos/standing/standing_0.mp4 --write_video ./videos/output/standing/standing_0.mp4 --write_json ./videos/output/standing/keypoints_standing_0.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/standing/standing_1.mp4 --write_video ./videos/output/standing/standing_1.mp4 --write_json ./videos/output/standing/keypoints_standing_1.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/standing/standing_2.mp4 --write_video ./videos/output/standing/standing_2.mp4 --write_json ./videos/output/standing/keypoints_standing_2.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/standing/standing_3.mp4 --write_video ./videos/output/standing/standing_3.mp4 --write_json ./videos/output/standing/keypoints_standing_3.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1

./build/examples/openpose/openpose.bin  --video ./videos/sleeping/sleeping_0.mp4 --write_video ./videos/output/sleeping/sleeping_0.mp4 --write_json ./videos/output/sleeping/keypoints_sleeping_0.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sleeping/sleeping_1.mp4 --write_video ./videos/output/sleeping/sleeping_1.mp4 --write_json ./videos/output/sleeping/keypoints_sleeping_1.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sleeping/sleeping_2.mp4 --write_video ./videos/output/sleeping/sleeping_2.mp4 --write_json ./videos/output/sleeping/keypoints_sleeping_2.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1
./build/examples/openpose/openpose.bin  --video ./videos/sleeping/sleeping_3.mp4 --write_video ./videos/output/sleeping/sleeping_3.mp4 --write_json ./videos/output/sleeping/keypoints_sleeping_3.json  --keypoint_scale 3 --display 0 --logging_level 4 —-number_people_max 1